# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(editable=False, unique=True)),
                ('payment_no', models.PositiveIntegerField(editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_no', models.PositiveIntegerField(unique=True)),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, b'REAL'), (1, b'TEST')])),
                ('sys_invs_no', models.PositiveIntegerField()),
                ('sys_trans_no', models.PositiveIntegerField()),
                ('sys_trans_date', models.DateTimeField()),
                ('payer_purse', models.CharField(max_length=13)),
                ('payer_wm', models.CharField(max_length=12)),
                ('paymer_number', models.CharField(blank=True, max_length=30)),
                ('paymer_email', models.EmailField(blank=True, max_length=254)),
                ('telepat_phonenumber', models.CharField(blank=True, max_length=30)),
                ('telepat_orderid', models.CharField(blank=True, max_length=30)),
                ('payment_creditdays', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='webmoney.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Purse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purse', models.CharField(max_length=13, unique=True)),
                ('secret_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payee_purse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='webmoney.Purse'),
        ),
    ]
